/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.45
 * Generated at: 2017-09-08 10:57:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1503534018000L));
    _jspx_dependants.put("jar:file:/D:/JIKYUNGHEE/Project_final/eclipse-work/wtpwebapps/MiniProject2/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<script>\t\r\n");
      out.write("\tfunction goLogin(){\r\n");
      out.write("\t\tlocation.href = \"/MiniProject2/login/login.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction upload(){\r\n");
      out.write("\t\tlocation.href = \"/MiniProject2/member/upload.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("  <head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title> J O I N </title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"/MiniProject2/Resources/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template -->\r\n");
      out.write("    <link href=\"/MiniProject2/Resources/css/business-casual.css\" rel=\"stylesheet\">\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topMenu.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("   \t<hr class=\"divider\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"bg-faded p-4 my-4\">\r\n");
      out.write("        <!-- Welcome Message -->\r\n");
      out.write("        <div class=\"text-center mt-4\">\r\n");
      out.write("          <div class=\"text-heading text-muted text-lg\">Welcome To</div>\r\n");
      out.write("          <h1 class=\"my-2\"> J O I N </h1>\r\n");
      out.write("          <div class=\"text-heading text-muted text-lg\">By\r\n");
      out.write("            <strong>팀 명</strong>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"bg-faded p-4 my-4\">\r\n");
      out.write("        <hr class=\"divider\">\r\n");
      out.write("        <h2 class=\"text-center text-lg text-uppercase my-0\">\r\n");
      out.write("          <strong> U S E R </strong>\r\n");
      out.write("        </h2>\r\n");
      out.write("        <hr class=\"divider\">\r\n");
      out.write("        <div align=\"center\" float=\"left\">\r\n");
      out.write("        \t<form name=\"lform\" action=\"");
      out.print( request.getContextPath());
      out.write("/joinProcess.do\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("\t\t\t\t<table style=\"width:65%\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\">Name</label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type = \"text\" class=\"form-control\" name = \"name\" size =\"20px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t<th><label class=\"text-heading\">&nbsp;&nbsp;&nbsp;Picture</label><input type=\"file\" name=\"upload\" value=\"upload\"/></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\">  E M A I L  </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type = \"email\" class=\"form-control\" name = \"id\" size =\"20px\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\">PASSWORD</label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type =\"password\" class=\"form-control\" name = \"password\" size =\"20px\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\">NICKNAME</label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type =\"text\" class=\"form-control\" name = \"nickname\" size =\"20px\"/></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\">  S E X  </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"M\"/>&nbsp;&nbsp;MEN&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"sex\" value=\"W\" size =\"20px\"/>&nbsp;&nbsp;WOMEN\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\">  P E T N O  </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"petNO\" style=\"width: 175px\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\"> T E L </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type = \"text\" class=\"form-control\" name = \"tel\" size =\"20px\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th width=\"30%\"><label class=\"text-heading\"> A D D R E S S </label></th>\r\n");
      out.write("\t\t\t\t\t\t<td><textArea name=\"basic_addr\" class=\"form-control\" rows=\"3\" cols=\"40\"></textArea></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<br/><br/>\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\" onclick='goLogin()'>CANCLE</button>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-secondary\"> N  E  X  T </button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("        <hr class=\"divider\">\r\n");
      out.write("        <!-- <img class=\"img-fluid float-left mr-4 d-none d-lg-block\" src=\"/miniProject_02/Resources/img/intro-pic.jpg\" alt=\"\"> -->\r\n");
      out.write("      </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- /.container -->\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript -->\r\n");
      out.write("    <script src=\"/MiniProject2/Resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/MiniProject2/Resources/vendor/popper/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"/MiniProject2/Resources/vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
